### ISSUE TITLE
Embedding QuML player in front end framework React Native

### ISSUE THREAD

**Issue by sajeshkayyath** [Sunbird-inQuiry/player#34]
**Project Details**
---
**What is Sunbird inQuiry?**

Sunbird inQuiry is a software building block that enables setting up of question banks for various use cases such as assessments, quizzes, practice worksheets, surveys, and many more. These are applicable in multiple domains related to education and human development. 
Here are some examples of solutions that can be enabled through Sunbird inQuiry:
Conduct assessments which can evaluate users’ understanding of concepts and issue certificates based on assessment score. 
Evaluate assessment data to take informed decisions and plan for interventions. 
Launch surveys to collect feedback and analyse responses. 

**Question Set Player (QuML player)**

Question set player is a player provided by inQuiry to create engaging & inclusive experiences for end users consuming the question sets. 

**Features to be implemented**
---
**Embedding QuML player in front end framework React Native**

QuML player is build as a web component and as part of this use case, we need to prepare a working version of QuML player using React Native. Currently our application is build on Angular and is not leveraging the web component of the player. With this in place, developers can leverage the player in the React Native applications and enhance the functionalities to meet their specific needs.

**What exists**

- Angular version of the [application](https://github.com/Sunbird-inQuiry/player/tree/release-5.6.0/projects/quml-demo-app) using the QuML player library
- QuML Player is available as [web component](https://github.com/Sunbird-inQuiry/player/tree/release-5.6.0/web-component)
- Backend APIs that is needed for the application to function

**What needs to be build**
 
- [ ] React native application embedding QuML player
- [ ] Fixing any integration issues while embedding the QuML player

**Learning Path**
---

**Complexity**
Medium

**Skills Required**
React Native

**Name of Mentors**
@rajnishdargan 

**Project size**
?? Weeks - TBD

**Product Set Up**
---
Instruction to install the application is available [here](https://github.com/Sunbird-inQuiry/player/tree/release-5.6.0)

**Acceptance Criteria**
---
- [ ]  QuML player is able to play all the questions in the React Native application
- [ ]  User is able to go through all the questions in the question set and answer

**Out of Scope**
---
Enhancing the existing angular application

**Milestones**
---
- [ ]  Understanding the requirements
- [ ]  Understanding QuMl Player
- [ ]  Setting up the app
- [ ]  Understanding the web component of QuML Player
- [ ]  Embedding the QuML Player inside the React Native application
- [ ]  Testing the application to cover the use cases

**Comment by AbhiiNaithani** [comment]
Hey @sajeshkayyath ,  I've found this project great and would like to contribute in this. I've some earlier experience in react-native app development and want to improve my skills through this project. Please guide me.

**Comment by Abro0058T** [comment]
Hey @sajeshkayyath , I saw the project and would like to contribute in this . I've experience in react-native and  would like to contribute in this project and  enhance my skills

**Comment by chandra-pro** [comment]
Hey @sajeshkayyath , I am interested to contribute in this project . I've already resolved some issue in one of the GovTech project using React Native.

**Comment by Amit2508** [comment]
Is any issue open ?

**Comment by ayushtiwari110** [comment]
Hey There! @sajeshkayyath 
I trust this correspondence finds you well. My name is Ayush Tiwari, and I am an Undergraduate student currently enrolled at the esteemed Indian Institute of Technology, Bhubaneswar. I just gone through this issue and I firmly believe that my proficiencies in React Native and other associated web technologies make me well-suited to contribute to its resolution.

Within the confines of my academic institution, I have had the privilege of engaging in the development of practical projects utilizing frameworks like ReactJS and React Native. These endeavors have equipped me with valuable experience in constructing applications that resonate with real-world demands. I had made two real world applications based on React Native. Moreover, I possess a commendable understanding of UI/UX design principles, further bolstering my capability to make valuable contributions.

In light of my qualifications and enthusiasm for this undertaking, I am eager to submit a comprehensive proposal outlining my strategic approach to the project. This detailed plan will elucidate my thought process and demonstrate how my involvement can be of utmost value to the initiative.

Thank you for dedicating your time to reviewing this communication. I look forward to the opportunity to contribute to the project and eagerly await your favorable response.

**Comment by sandeepB3** [comment]
Can anyone help me with this issue ? Is this 'https://staging.sunbirded.org/api/question/v1/list' api working? I am trying to use quml player as a web component and when I make request to the above url to get list of questions it shows error. Any other API is there ?

**Comment by vaibhavbhuva** [comment]
> Can anyone help me with this issue ? Is this 'https://staging.sunbirded.org/api/question/v1/list' api working? I am trying to use quml player as a web component and when I make request to the above url to get list of questions it shows error. Any other API is there ?

@sandeepB3 Please share more details on what error you are getting so we can help you the same.

**Comment by vaibhavbhuva** [comment]
Hi All, 
Thanks for your interest in our project. please do setup the application locally, also make sure to prepare and submit your proposal in unstop platform and join discord [channel](https://discord.com/channels/973851473131761674/1106637310042329159) for continuous updates.

**Comment by turingAlan** [comment]
Hi @vaibhavbhuva,
I found this project really interesting as I have been developing both android and iOS application using react native for more than 2 years for my clients now, I would also like to try my hands on open-source contribution. Looking forward towards contributing in this project.

**Comment by vaibhavbhuva** [comment]
@turingAlan Thanks for showing interest in this project. 
Please check out the C4GT website on how you can contribute: https://www.codeforgovtech.in/.

**Comment by santhosh-tarento** [comment]
![image](https://github.com/Sunbird-inQuiry/player/assets/120555456/c0d3782e-b689-4242-a3e0-67cac47f5ef5)
@all, With Fork player repo I create player library and published in npm, while using that in sunbirdED portal I am getting below error, so Is there dependency missing, please help me with it
FYI.. ViewerService is become undefined. @vaibhavbhuva @sajeshkayyath
