### ISSUE TITLE
Enhance QuML player for new question types

### ISSUE THREAD

**Issue by kiranharidas187** [Sunbird-inQuiry/player#36]
### Project Details

QuML(Question Markup Language) defines a standard format for the representation of questions, tests, and their results, supporting the exchange of this material between authoring and delivery systems, repositories, and other e-learning systems. With the help of QuML, we can create a bank of questions so that all the systems which follow the same specification can use it. Anyone can create a new type of question by defining the new meta values for the defined specification. For more ref  https://quml.sunbird.org/

QuML player is the name of tool/library used to render the different types of questions (that follow QuML specification) for the end user for both the app and portal.

### Features to be implemented

Enable the QuML player to render with following new types of questions

- Number - This type of question will only accept numbers as input
- Text - This type of question will accept all types of characters as input
- Slider - This type of question accept values between a specific range(number only)
- Date - This type of question accepts the date as the input
- Single select - This is radio type of questions
- Multiselect - This is a checkbox-type question
- Matrix type question - This type of question consists of a group above-mentioned question types. This group of questions can be repeated n number of times similar to a mathematical matrix
- 

New additional features for all questions types

- Dependent question - For Single select and multi-select questions, user can add dependent question ie there can be parent and child relationship between the questions.
- Remarks - Render or hide the remarks section based on the question config
- Attacments - Allow used to attach the evidences as per the config

### Learning Path

**Complexity**
Medium

**Skills Required**
Angular , HTML , CSS

**Name of Mentors:**
Ramkumar - @ramkumar-pacewisdom

**Project size**
8 weeks

**Product Set Up**
Instruction to install the application is available [here](https://github.com/Sunbird-inQuiry/player/tree/release-5.7.0)

**Acceptance Criteria**
All types of questions should be rendered using this player

### Milestones

- [ ] Understanding the requirements
- [ ] Understanding QuMl Player
- [ ] Setting up the app
- [ ] Understanding the web component of QuML Player
- [ ] Implementing the capability to render new question types
- [ ] Add additional features for all types of questions
- [ ] Change the layout of the player

**Comment by Prakhar-commits** [comment]
Hey there I would Like to work on this issue

**Comment by shreyaspande2003** [comment]
hello @kiranharidas187 mentor sir .. To introduce myself, I am proficient in Python and creating web apps for different purposes and am passionate about getting to know about new techstacks . and I see this as an interesting project. 
 can I get to know about on which background the app is created to know about about how the original questions were generated and then I would think about how can we implement the new meta values.. 
looking forward to connect with you and discuss the project further.

Thanks

**Comment by ramkumar-pacewisdom** [comment]
Hi @shreyaspande2003 
I'm a mentor for this project and Thanks for you interest. This is an angular library to render different types of questions (that follow QuML specification) for the end user for both the app and portal. 
And this library Built on **Angular(Front-end)** and no role in this repo for **backend**. The questions for player will be originally created in [sunbird editor](https://github.com/Sunbird-inQuiry/editor) and app. Basically our own library itself will have set of static questions to render, so no need to lookout for external app support from other apps while development.

I hope above details would clear you doubts, if you need more clarity on anything we discuss here or kindly post your questions in discord [channel](https://discord.com/channels/973851473131761674/1106637090625703987).

**Comment by KOWSHIQKATTAMURI** [comment]
Hello QuML Team,

I hope this message finds you well. My name is Kowshiq Kattamuri, and I am an upcoming fourth-year student at NIT Calicut. I have experience working with the MERN stack and have developed an e-commerce website in the past. I am excited about the opportunity to contribute to the QuML Player project and believe that my skills in Angular, HTML, and CSS will be valuable in implementing the desired features. 

I am particularly interested in working on the new question types and additional features for the QuML Player. I have a few ideas on how to approach the tasks that are mentioned above. 

I'm excited to contribute to this project and aid in expanding the capabilities of the QuML Player. My experience in web development and my love of making user-friendly interfaces will be a benefit to the team, in my opinion. I'm eager to expand on my ideas and discover how I can most effectively help the project succeed.

**Comment by kkartik07** [comment]
Hello everyone!
I am Kartik Kankurte, a undergraduate student from Indian Institute of Technology, Varanasi (BHU). I have experience building frontend for many web apps. I have previously used React for building many websites for my projects and used Vue.js in my previous internship. I have also contributed to some open sourced organizations and found this project to be very interesting. I think I can easily work with Angular also.  So I would like to contribute to this project. 
Thank you.

**Comment by ramkumar-pacewisdom** [comment]
@kkartik07 please reach out us in discord channel, so everyone can understand if they are facing similar issues and we can discuss.

**Comment by ramkumar-pacewisdom** [comment]
@bha123nu @kkartik07 @KOWSHIQKATTAMURI @shreyaspande2003 we're conducting our first Q&A and issue clarification session today, if you're interested please join through the meet link i added below. Looking forward to meet you all in the session. Thank you.
click this link: Samagra discussion
Wednesday, May 24 · 10:00 – 10:30am
Time zone: Asia/Kolkata
Google Meet joining info
Video call link: [Meel link](https://meet.google.com/ovd-sivb-yhz)

**Comment by sivaraju5609** [comment]
hello everyone !

this siva raju i am very much intrested to contribute this project i have a knowledge on above langauges i had built some web applications by using above langauges i am very enthusiastic to be a contribute this project

**Comment by hetvi-45** [comment]
Hello everyone
I would like to contribute in this project. I have good knowledge of required tech stack and have few ideas on how to approach the tasks that are mentioned above.

**Comment by ramkumar-pacewisdom** [comment]
@sivaraju5609 @hetvi-45 Thanks for your interest, please join in discord [channel](https://discord.com/channels/973851473131761674/1106637090625703987) for continuous updates and please do setup application in local, also make sure to prepare and submit your proposal in unstop platform.

**Comment by Ayushi5178** [comment]
hello mentor 
As a CSE student I have a prior knowledge of development and i did many internships in this field and i am willing to contribute in this project
Thank you

**Comment by ramkumar-pacewisdom** [comment]
@Ayushi5178 thanks for your interest, please join in discord [channel](https://discord.com/channels/973851473131761674/1106637090625703987) for continuous updates and please do setup application in local, also make sure to prepare and submit your proposal in unstop platform.

**Comment by Ishitag26** [comment]
Greetings of the day @ramkumar-pacewisdom  Sir,

My name is Ishita Gupta, currently pursuing my Bachelors of Technology from Rajasthan Technical University. I was going through this issue recently and my proficiencies and skillsets in are perfect suite for me to contribute.

I have previously worked on creating reliable and flexible apps via ReactJS . In some of my projects, I have worked on APIs and components, so I am aware about how the data flow works between various parts. These activities have given me invaluable expertise in creating applications that speak to needs in the real world. I think I can easily go on working with Angular as well.

 I'm committed to making a significant effort, following accepted coding guidelines, and applying best practices. I firmly believe in open communication and teamwork, and I am looking forward to actively participating in discussions, offering my ideas, and taking into consideration community feedback.

Thankyou!

**Comment by ramkumar-pacewisdom** [comment]
Hi @Ishitag26, Thanks for your interest in our project. please join in discord [channel](https://discord.com/channels/973851473131761674/1106637090625703987) for continuous updates and please do setup application in local, also make sure to prepare and submit your proposal in unstop platform.

**Comment by vinayastar01** [comment]
I am Vinay Kumar, final year student at NIT Allahabad. I really interested to work on this project.

**Comment by mahi674** [comment]
Greetings of the day @ramkumar-pacewisdom Sir,

I am Mahi Mittal, a second-year student at Banasthali University. I hope this message finds you  in good health. I am reaching out today with great enthusiasm as I would like to offer my knowledge and skills to contribute to this project.
Allow me to begin by mentioning that this is my first venture into a project of this nature. However, I am highly motivated to learn and grow, and I believe my dedication and enthusiasm will make a positive impact.
I understand that embarking on a new project requires a certain level of expertise and experience. However, I am eager to collaborate  and contribute my unique perspective and fresh ideas. I am a quick learner and will dedicate myself wholeheartedly to understand and fulfill the project requirements.

**Comment by ramkumar-pacewisdom** [comment]
@mahi674 @vinayastar01 Thanks for your interest in our project. please join in discord [channel](https://discord.com/channels/973851473131761674/1106637090625703987) for continuous updates and please do setup application in local, also make sure to prepare and submit your proposal in unstop platform.

**Comment by PRANITHA1409** [comment]
Hi, my name is pranitha
I found this project intresting and i'm intrested in working with angular so would like to join discord channel.

**Comment by ramkumar-pacewisdom** [comment]
Hi @PRANITHA1409, Thanks for your interest in our project. please do setup application in local, also make sure to prepare and submit your proposal in unstop platform and join in discord [channel](https://discord.com/channels/973851473131761674/1106637090625703987) for continuous updates.

**Comment by Deepika-jangraa** [comment]
Hello dear sir,
I have completed MCA recently, where I learn about javascript angular html css and many more languages. I go through the project and I'm interested in it.
Thanks for the opportunity.

**Comment by Loonymetzi** [comment]
Hello mentor,
I am Prachi Jha, I'm an undergraduate student of Computer Science and engineering from Birla Institute of technology. I'm an avid web developer and have created numerous personal projects using HTML, CSS and other Javascript frameworks and libraries. I'm looking forward to contributing!
Thank You!
